<?php
/**
 * Admin - Receipts ledger (all issued receipts).
 */
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../includes/finance.php';

requireRole('admin');

$pageTitle = 'Receipts';
$activeMenu = 'receipts';
$extraCss   = 'admin/payments/assets/css/payments.css';

$db    = getDBConnection();
$search = trim($_GET['search'] ?? '');

$sql = "
    SELECT r.receipt_id, r.receipt_number, r.created_at, r.generated_by,
           p.payment_id, p.amount, p.refunded_amount, p.payment_method, p.paid_at, p.transaction_ref,
           i.invoice_id, i.invoice_number,
           CONCAT(c.first_name,' ',c.last_name) AS client_name,
           CONCAT(u.first_name,' ',u.last_name) AS generated_by_name
    FROM receipts r
    JOIN payments p ON p.payment_id = r.payment_id
    LEFT JOIN invoices i ON i.invoice_id = p.invoice_id
    LEFT JOIN clients c ON c.client_id = COALESCE(p.client_id, i.client_id)
    LEFT JOIN users u ON u.user_id = r.generated_by
";
$params = [];
if ($search !== '') {
    $sql .= " WHERE r.receipt_number LIKE :s1 OR i.invoice_number LIKE :s2 OR CONCAT(c.first_name,' ',c.last_name) LIKE :s3";
    $params[':s1'] = '%' . $search . '%';
    $params[':s2'] = '%' . $search . '%';
    $params[':s3'] = '%' . $search . '%';
}
$sql .= " ORDER BY r.receipt_id DESC LIMIT 300";

$stmt = $db->prepare($sql);
$stmt->execute($params);
$receipts = $stmt->fetchAll();
?>
<?php require_once __DIR__ . '/../includes/header.php'; ?>

<div class="page-head">
    <div class="page-head-title">
        <h1><i class="fas fa-receipt"></i> Receipts</h1>
        <p>Every collected payment issue a uniquely numbered receipt.</p>
    </div>
</div>

<div class="admin-card">
    <div class="card-header-custom flex-wrap gap-2">
        <h5><i class="fas fa-ticket"></i> All Receipts <span class="status-badge confirmed" style="margin-left:.5rem;"><?php echo count($receipts); ?></span></h5>
        <form method="get" class="d-flex gap-2">
            <div class="filter-search">
                <i class="fas fa-magnifying-glass"></i>
                <input type="text" name="search" value="<?php echo sanitize($search); ?>" placeholder="Receipt, invoice or client…" class="form-control-admin form-control-sm">
            </div>
            <button class="btn-admin btn-cyan btn-xs"><i class="fas fa-filter"></i> Filter</button>
            <?php if ($search !== ''): ?><a href="<?php echo SITE_URL; ?>/admin/receipts/index.php" class="btn-admin btn-outline btn-xs">Clear</a><?php endif; ?>
        </form>
    </div>

    <?php if (!$receipts): ?>
    <div class="empty-state"><i class="fas fa-receipt"></i><h5>No receipts yet</h5><p>Receipts are issued automatically when a payment is collected.</p></div>
    <?php else: ?>
    <div class="table-scroll">
        <table class="admin-table">
            <thead>
                <tr>
                    <th>Receipt</th>
                    <th>Issued</th>
                    <th>Invoice</th>
                    <th>Client</th>
                    <th>Method</th>
                    <th class="fin-amount">Amount</th>
                    <th>Payment</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($receipts as $r): ?>
                <tr>
                    <td><strong><?php echo sanitize($r['receipt_number']); ?></strong></td>
                    <td><?php echo formatDate($r['created_at'], 'M d, Y g:i A'); ?></td>
                    <td>
                        <?php if ($r['invoice_number']): ?><a class="text-cyan-link" href="<?php echo SITE_URL; ?>/admin/invoices/view.php?id=<?php echo (int)$r['invoice_id']; ?>"><?php echo sanitize($r['invoice_number']); ?></a><?php else: ?>—<?php endif; ?>
                    </td>
                    <td><?php echo sanitize($r['client_name'] ?? '—'); ?></td>
                    <td><?php echo sanitize(ucfirst(str_replace('_', ' ', $r['payment_method']))); ?></td>
                    <td class="fin-amount"><?php echo formatMoney($r['amount']); ?></td>
                    <td><a class="text-cyan-link" href="<?php echo SITE_URL; ?>/admin/payments/view.php?id=<?php echo (int)$r['payment_id']; ?>">#<?php echo (int)$r['payment_id']; ?></a></td>
                    <td><?php echo $r['generated_by_name'] ? sanitize($r['generated_by_name']) : '—'; ?></td>
                    <td><a class="btn-admin btn-outline btn-xs" target="_blank" href="<?php echo SITE_URL; ?>/admin/receipts/print.php?receipt_id=<?php echo (int)$r['receipt_id']; ?>" title="Print"><i class="fas fa-print"></i></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>